#!/bin/bash

# Halt if virtualenv or pip are not installed
for command in virtualenv pip; do
	which $command &> /dev/null
	if [ $? -ne 0 ]; then
		echo -e "! Check if $command is installed";
		exit 1
	fi
done

# Create some folders
mkdir -p logs uploads
mkdir scripts/{bin,ref}

# Create a nice virtual environment
virtualenv .
source ./bin/activate

# Install required modules
pip install -r requirements.txt

# Don't track settings.py and the run script
echo -e "scripts/run.sh" >> ./.gitignore
echo -e "settings.py" >> ./.gitignore

# Generate secret key
secret_key=$(openssl rand -base64 24)
echo -e "SECRET_KEY = \"$secret_key\"" >> settings.py

# Get the YUI compressor
mkdir misc && cd misc
wget https://github.com/downloads/yui/yuicompressor/yuicompressor-2.4.7.zip
unzip ./yuicompressor-2.4.7.zip
mv yuicompressor-2.4.7 yui
rm yuicompressor-2.4.7.zip
cd ..
