#!/bin/bash

# You'll need Python 2.7+ for this application. RHEL, notably,
# uses 2.6 as default. Change this variable to wherever you've 
# compiled Python 2.7. 
# E.g.
# PYTHON_PATH="/usr/bin/python2.7"
PYTHON_PATH=$(which python)

# Halt if virtualenv or pip are not installed
for command in virtualenv pip; do
	which $command &> /dev/null
	if [ $? -ne 0 ]; then
		echo -e "! Check if $command is installed";
		exit 1
	fi
done

# Warning about Python 2.7
echo -e "
! Things won't work if you don't have Python 2.7+
  Cancel in the next few seconds if you don't.
  See README.md or edit this file if you've compiled
  it for your platform.
"
echo -n "You're currently using "
$PYTHON_PATH --version
sleep 9

# Create a nice virtual environment
virtualenv -p $PYTHON_PATH .
source ./bin/activate

# Install required modules
pip install -r requirements.txt

# Create some folders and logfiles
mkdir -p logs uploads
touch logs/nginx.{access,error}.log

# Don't track a few files
echo -e "install" >> ./.gitignore
echo -e "scripts/run.sh" >> ./.gitignore
echo -e "settings.py" >> ./.gitignore

# Generate secret key
secret_key=$(openssl rand -base64 24)
echo -e "SECRET_KEY = \"$secret_key\"" >> settings.py

# Get the YUI compressor
mkdir misc && cd misc
wget https://github.com/downloads/yui/yuicompressor/yuicompressor-2.4.7.zip
unzip ./yuicompressor-2.4.7.zip
mv yuicompressor-2.4.7 yui
rm yuicompressor-2.4.7.zip
cd ..
