#!/bin/bash

# Halt if virtualenv or pip are not installed
for command in virtualenv pip; do
	which $command &> /dev/null
	if [ $? -ne 0 ]; then
		echo -e "! Check if $command is installed";
		exit 1
	fi
done

# Create some folders
mkdir -p logs uploads

# Create a nice virtual environment
virtualenv .
source ./bin/activate

# Install required modules
pip install -r requirements.txt

# Generate secret key
secret_key=$(openssl rand -base64 24)
echo -e "SECRET_KEY = \"$secret_key\"" >> settings.py
