#!bin/python

import os
import sys
import logging

from lockfile.pidlockfile import PIDLockFile
from autozygosity import app
from settings import *

# Run flask or gunicorn depending on options
# Default is gunicorn
if len(sys.argv) == 2 and sys.argv[1] == "flask":
    from autozygosity import app
    app.run(host = HOST, debug = True, port = PORT)
else:
    os.system("gunicorn --workers 10 --bind " + HOST + ":" + str(PORT) + " autozygosity:app --daemon --access-logfile ./logs/access_log --error-log ./logs/error_log --debug --pid ./daemon.pid --timeout=120 --graceful-timeout=30")

