#!bin/python

import os
import sys
import logging

from lockfile.pidlockfile import PIDLockFile
from werkzeug.serving import run_simple
from autozygosity import routed_app
from settings import *

# Run flask or gunicorn depending on options. Default is gunicorn.
if len(sys.argv) == 2 and sys.argv[1] == "flask":
    run_simple(HOST, PORT, routed_app, use_reloader=True, use_debugger=DEBUG)
else:
    os.system("gunicorn --workers 10 --bind " + HOST + ":" + str(PORT) + " autozygosity:routed_app --daemon --access-logfile ./logs/gunicorn.access.log --error-log ./logs/gunicorn.error.log --debug --pid ./daemon.pid --timeout=120 --graceful-timeout=30")
