#!/bin/bash

if [[ ! -e ./daemon.pid ]]; then
    echo -e "! Couldn't find PID file. Sure the daemon's running?"
    exit
fi

DAEMON_PID=$(cat ./daemon.pid)

echo -n "Stopping server with PID $DAEMON_PID..."
kill -9 $DAEMON_PID
rm ./daemon.pid

